### ISSUE TITLE
Where does Builder.io fit into this?

### ISSUE THREAD

**Issue by MarioRicalde** [BuilderIO/html-to-figma#2]
I think it would be wise to add somewhere in the README ( and maybe the plugin description ), where builder.io fits into the plugin.

How does it work? Is something happening on the builder.io servers - if so, what? Is there any data stored over there? Is it a service? Will it have a pricing tag?

**Comment by steve8708** [comment]
Hi @MarioRicalde, thanks for the question. 

This plugin was purely made by me to make my life easier, and I also made Builder.io so I figured why not include it under the company's Github account and mention that it was made by me so some people might discover that Builder.io exists who would find it useful that otherwise don't know about it.

I, for free, have created an API that hosts the `lib` part of the code here so the extension can run the code on a backend using [puppeteer](https://github.com/GoogleChrome/puppeteer). This extension wouldn't be possible purely client side, it requires a backend to run the loading of the URL you enter into a headless browser and processing it to find all of the necessary dom elements that need to be converted to Figma layers and calculating their sizes, positions, and styles. 

I don't store any data, and this will forever be free.

I am also experimenting with a way to use this plugin (or maybe a separate one, TBD) to take a Figma design and import it into Builder.io so you can turn your designs into a live website easily, or turn it into code (html/css, React, Vue, etc)

**Comment by MarioRicalde** [comment]
Amazing - thank you for the explanation. Makes perfect sense, it might be a good idea to put this somewhere that is visible. Might help other people.

Cheers!
