### ISSUE TITLE
Request: Allow user to specify page width

### ISSUE THREAD

**Issue by Subcide** [BuilderIO/html-to-figma#7]
If we could specify a pixel width value, it'd allow us to capture mobile responsive versions, and more easily map to screen sizes we might be designing for on desktop also.

**Comment by steve8708** [comment]
Hey @Subcide - you're in luck, this is possible, but since this is reported twice I should definitely make it more obvious! I will leave this open until I made a new UI putting this more front and center, but in the meantime here is how to specify width 

![import screen sizes](https://user-images.githubusercontent.com/844291/64193583-e90a5a80-ce31-11e9-8612-c37f5d945ca1.gif)
